Repository JoomGalleryfriends/JoomGallery, pull requests merged in 2025-08, with the labels that each got.

#236 [Feature] Edit in media manager button
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/src/Controller/ImageController.php
  administrator/com_joomgallery/tmpl/image/edit.php
Labels: needs testing, GUI testing

#218 [Feature] CLI: function Added plugin console/joomconsole
  administrator/com_joomgallery/src/CliCommand/Category.php
  administrator/com_joomgallery/src/CliCommand/CategoryAdd.php
  administrator/com_joomgallery/src/CliCommand/CategoryList.php
  administrator/com_joomgallery/src/CliCommand/CategoryParams.php
  administrator/com_joomgallery/src/CliCommand/Config.php
  administrator/com_joomgallery/src/CliCommand/ConfigDynprocessing.php
  administrator/com_joomgallery/src/CliCommand/ConfigGet.php
  administrator/com_joomgallery/src/CliCommand/ConfigList.php
  administrator/com_joomgallery/src/CliCommand/ConfigSet.php
  administrator/com_joomgallery/src/CliCommand/Image.php
  administrator/com_joomgallery/src/CliCommand/ImageList.php
  administrator/com_joomgallery/src/CliCommand/ImageMetadata.php
  administrator/com_joomgallery/src/CliCommand/ImageParams.php
  joomgallery.xml
  plugins/console/joomconsole/joomconsole.xml
  plugins/console/joomconsole/language/en-GB/en-GB.plg_console_joomconsole.ini
  plugins/console/joomconsole/language/en-GB/en-GB.plg_console_joomconsole.sys.ini
  plugins/console/joomconsole/services/provider.php
  plugins/console/joomconsole/src/Extension/JoomgalleryConsole.php
Labels: enhancement, needs testing

#251 [Feature] Two new config options for description/label in the Category View
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.2.0.sql
  site/com_joomgallery/layouts/joomgallery/grids/images.php
  site/com_joomgallery/layouts/joomgallery/grids/subcategories.php
  site/com_joomgallery/tmpl/category/default.xml
  site/com_joomgallery/tmpl/category/default_cat.php
Labels: enhancement, needs testing, DB changed, frontend

#252 [Fix] Allow multiple justified grids
  media/com_joomgallery/js/joomgrid.js
Labels: needs testing, GUI testing

#256 [Feature] Change max filesize to MB
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.2.0.sql
Labels: DB changed, GUI testing

#261 [Refactor] Remove fields table
  administrator/com_joomgallery/includes/defines.php
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.2.0.sql
  administrator/com_joomgallery/src/Helper/JoomHelper.php
  administrator/com_joomgallery/src/Table/FieldTable.php
  plugins/system/joomowner/src/Extension/JoomgalleryOwner.php
Labels: needs testing, DB changed
