Repository JoomGalleryfriends/JoomGallery, pull requests merged in 2025-07, with the labels that each got.

#214 [UX/UI] hide # images for infinite scroll pagination
  administrator/com_joomgallery/forms/config.xml
  site/com_joomgallery/tmpl/category/default.xml
Labels: backend, GUI testing

#207 [Feature] Metadata editing for JPG images
  .gitignore
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/forms/image.xml
  administrator/com_joomgallery/forms/subform_imageimgmetadata.xml
  administrator/com_joomgallery/forms/subform_metadata_exif.xml
  administrator/com_joomgallery/forms/subform_metadata_exif_exif.xml
  administrator/com_joomgallery/forms/subform_metadata_exif_ifd0.xml
  administrator/com_joomgallery/forms/subform_metadata_iptc.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.exif.ini
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/layouts/joomla/form/field/subform/exif.php
  administrator/com_joomgallery/services/provider.php
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.1.0.sql
  administrator/com_joomgallery/src/Controller/ImageController.php
  administrator/com_joomgallery/src/Extension/JoomgalleryComponent.php
  administrator/com_joomgallery/src/Field/ExifusercommentField.php
  administrator/com_joomgallery/src/Field/MetadatacommentField.php
  administrator/com_joomgallery/src/Model/ImageModel.php
  administrator/com_joomgallery/src/Model/TagsModel.php
  administrator/com_joomgallery/src/Service/IMGtools/GDtools.php
  administrator/com_joomgallery/src/Service/Metadata/IptcDataEditor.php
  administrator/com_joomgallery/src/Service/Metadata/Metadata.php
  administrator/com_joomgallery/src/Service/Metadata/MetadataExifTool.php
  administrator/com_joomgallery/src/Service/Metadata/MetadataInterface.php
  administrator/com_joomgallery/src/Service/Metadata/MetadataPHP.php
  administrator/com_joomgallery/src/Service/Metadata/MetadataServiceInterface.php
  administrator/com_joomgallery/src/Service/Metadata/MetadataServiceTrait.php
  administrator/com_joomgallery/src/Service/Metadata/PelDataEditor.php
  administrator/com_joomgallery/src/Service/Uploader/Uploader.php
  administrator/com_joomgallery/src/Table/ImageTable.php
  administrator/com_joomgallery/src/View/Image/HtmlView.php
  administrator/com_joomgallery/tmpl/image/edit.php
  composer.json
  joomgallery.xml
  media/com_joomgallery/css/admin.css
Labels: needs testing, DB changed, GUI testing

#235 [Bugfix] Changelog button after update
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/language/en-GB/com_joomgallery.sys.ini
  script.php
  site/com_joomgallery/language/en-GB/com_joomgallery.ini
Labels: needs testing, GUI testing

#239 Release v4.1.0
  administrator/com_joomgallery/sql/updates/mysql/4.1.0.sql
  administrator/com_joomgallery/src/Service/Metadata/IptcDataEditor.php
  administrator/com_joomgallery/src/Service/Metadata/Metadata.php
  administrator/com_joomgallery/src/Service/Metadata/MetadataExifTool.php
  administrator/com_joomgallery/src/Service/Metadata/MetadataPHP.php
  administrator/com_joomgallery/src/Service/Metadata/PelDataEditor.php
  joomgallery.xml
  plugins/privacy/joomgallery/joomgallery.xml
  plugins/system/joomgallery/joomgallery.xml
  plugins/system/joomowner/joomowner.xml
Labels: needs testing, GUI testing

#241 Fix update issue in Joomla! < v5.1
  script.php
Labels: bug, needs testing, GUI testing

#244 Improve zip creation script
  .github/workflows/pr-build.yml
  .github/workflows/release.yml
Labels: needs testing, GUI testing
