Repository JoomGalleryfriends/JoomGallery, pull requests merged in 2025-05, with the labels that each got.

#166 Add a description in Gallery View
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  site/com_joomgallery/src/Model/GalleryModel.php
  site/com_joomgallery/tmpl/gallery/default.php
  site/com_joomgallery/tmpl/gallery/default.xml
Labels: enhancement, needs testing, frontend

#181 Adjustment of the Meta Description
  administrator/com_joomgallery/forms/category.xml
  administrator/com_joomgallery/forms/collection.xml
  administrator/com_joomgallery/forms/image.xml
  site/com_joomgallery/forms/categoryform.xml
  site/com_joomgallery/forms/imageform.xml
Labels: backend, GUI testing

#182 Add a setting for the alignment of category titles
  administrator/com_joomgallery/forms/config.xml
  administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.1.0.sql
  site/com_joomgallery/tmpl/category/default_cat.php
Labels: needs testing, DB changed

#200 Fix button layout in control panel
  administrator/com_joomgallery/src/View/Control/HtmlView.php
  administrator/com_joomgallery/tmpl/control/default.php
Labels: needs testing, backend

#203 Increase length of DB column fullpath
  administrator/components/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/components/com_joomgallery/sql/updates/mysql/3.7.1.sql
Labels: needs testing, backend, v3.x

#198 Increase speed of list views with pagination
  administrator/com_joomgallery/sql/install.mysql.utf8.sql
  administrator/com_joomgallery/sql/updates/mysql/4.1.0.sql
  administrator/com_joomgallery/src/Model/CategoriesModel.php
  administrator/com_joomgallery/src/Model/ConfigsModel.php
  administrator/com_joomgallery/src/Model/ImagesModel.php
  administrator/com_joomgallery/src/Model/JoomListModel.php
  administrator/com_joomgallery/src/Model/TagsModel.php
Labels: needs testing, DB changed, GUI testing

#186 Multiple image grids and lightGalleries
  media/com_joomgallery/js/joomgrid.js
  site/com_joomgallery/tmpl/category/default_cat.php
  site/com_joomgallery/tmpl/gallery/default.php
Labels: enhancement, needs testing, frontend, GUI testing

#211 [Fix] Filesystem during migration
  administrator/com_joomgallery/src/Model/MigrationModel.php
Labels: needs testing, GUI testing
